ALTER TABLE `spmsdb`.`EXCEL_UPLOAD` 
CHANGE COLUMN `PRODUCT_NAME` `PRODUCT_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '품명' AFTER `RECEIVE_POINT`,
ADD COLUMN `RECEIVER_ADDR_DO` VARCHAR(45) NULL AFTER `RECEIVER_ADDR`,
ADD COLUMN `RECEIVER_ADDR_KOO` VARCHAR(45) NULL AFTER `RECEIVER_ADDR_DO`,
ADD COLUMN `RECEIVER_ADDR_DONG` VARCHAR(45) NULL AFTER `RECEIVER_ADDR_KOO`,
ADD COLUMN `RECEIVER_ADDR_ROAD` VARCHAR(45) NULL AFTER `RECEIVER_ADDR_DONG`,
ADD COLUMN `RECEIVER_ADDR_BUN` INT NULL AFTER `RECEIVER_ADDR_ROAD`,
ADD COLUMN `RECEIVER_ADDR_JI` INT NULL AFTER `RECEIVER_ADDR_BUN`,
ADD COLUMN `RECEIVER_ADDR_NAME` VARCHAR(45) NULL AFTER `RECEIVER_ADDR_JI`;
